config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/about'
  get 'static_pages/contact'

  root 'static_pages#home'
  match '/new_recipe',  to: 'recipe#new', via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/models/hop.rb
class Hop < ActiveRecord::Base
  validates( :name, :uniqueness => { :case_senstive => false } )
  validates( :alpha, :numericality => { :greater_than => 0.0, :less_than => 25.0 } )
end

app/models/malt.rb
class Malt < ActiveRecord::Base
  validates( :name,       { :uniqueness =>   { :case_sensitive => false } } )
  validates( :potential,  { :numericality => { :greater_than => 1.020, :less_than => 1.050 } } )
  validates( :malt_yield, { :numericality => { :greater_than => 0.0, :less_than_or_equal_to => 1.0 } } )
  validates( :srm, { :numericality => { :greater_than => 0.0, :less_than => 800.0 } } )
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

  attr_accessor :name, :style, :abv, :ibu, :srm, :malts, :hops, :yeast, :og, :stack_token

  def initialize
    @malts = { :base => {}, :specialty => {} }
    @hops = { :bittering => {}, :aroma => [] }
    @name = "Beer"
    @stack_token = 0
    super
  end

  def choose_attributes
    self.assign_malts
    self.assign_hops
    self.assign_yeast
    self.calc_gravities
    self.calc_color
    self.calc_bitterness
    self.ibu_checks
    self.assign_style
    self.generate_name
  end

  def generate_name
    @name = @style.name unless @style.nil?
    check_smash
    add_yeast_family
    add_ingredient_to_name
    add_color_to_name
    nationality_check
    add_strength_to_name
    add_article
  end

  def check_smash
    smash = CheckSmash.new(@style, hop_names_to_array, @malts, malts_to_array, hops_to_array)
    smash_name = smash.check
    @name = smash_name unless smash_name == nil
  end

  def add_ingredient_to_name
    ingredient = AddIngredient.new(@name, malts_to_array, @style)
    add_adjective(@name, ingredient.add_ingredient)
  end

  def add_yeast_family
    yeast = AddYeast.new(@style, @name, @yeast)
    with_yeast = yeast.add_yeast
    @name = with_yeast if with_yeast != nil
  end

  def nationality_check
    nationality = CheckNationality.new(@name)
    @name = nationality.check
  end

  def add_color_to_name
    color = AddColor.new(@style, @name, @srm)
    add_adjective(@name, color.add_color)
  end

  def add_strength_to_name
    strength = AddStrength.new(@style, @name, @abv)
    add_adjective(@name, strength.add_strength)
  end

  def add_article
    @name = %w(a e i o u).include?(@name.strip[0].downcase) ? "An #{@name.strip}" : "A #{@name.strip}"
  end

  def add_adjective(name, adjective)
    adjective_adder = AddAdjective.new(@style)
    @name = adjective_adder.add_adjective(name, adjective)
  end

  def ibu_checks
    re_hop = ReAssignHops.new(self)
    re_hop.extreme_ibu_check
    re_hop.ibu_gravity_check
  end

  def assign_malts
    maltster = AssignMalts.new(self)
    store_malt(maltster.choose_malt(true))
    maltster.num_specialty_malts.times { store_malt(maltster.choose_malt(false)) }
    @malts[:specialty]= maltster.order_specialty_malts(@malts)
  end

  def store_malt(arg)
    type_key = arg[0]
    malt = arg[1]
    amt = arg[2]
    if @malts[type_key][malt].nil?
      @malts[type_key][malt]= amt
    else
      @malts[type_key][malt]+= amt
    end
  end

  def malts_to_array
    malt_ary = MaltsArrays.new(@malts)
    malt_ary.malts_to_array
  end

  def malt_names_to_array
    malt_ary = MaltsArrays.new(@malts)
    malt_ary.malt_names_to_array
  end

  def assign_hops
    hopster = AssignHops.new(self)
    store_hop(hopster.choose_hop(true))
    hopster.num_aroma_hops.times { store_hop(hopster.choose_hop(false)) }
  end

  def store_hop(arg)
    type_key = arg[0]
    hop = arg[1]
    amt = arg[2]
    time = arg[3]
    if type_key == :bittering
      @hops[type_key][hop]= [amt, time]
    else
      @hops[type_key] << { hop => [amt, time] }
    end
  end

  def hops_to_array
    hop_ary = HopsArrays.new(@hops)
    hop_ary.hops_to_array
  end

  def hop_names_to_array
    hop_ary = HopsArrays.new(@hops)
    hop_ary.hop_names_to_array
  end

  def assign_yeast
    pick_yeast = AssignYeast.new(@malts)
    if rand(3) == 0
      @yeast = pick_yeast.associate_yeast
    else
      @yeast = pick_yeast.choose_yeast
    end
  end

  def calc_gravities
    gravity = CalculateGravity.new(@yeast, malts_to_array)
    gravity_ary = gravity.calc_abv
    @og = gravity_ary[0]
    @abv = gravity_ary[1]
  end

  def calc_bitterness
    bitterness = CalculateBitterness.new(hops_to_array, @og)
    @ibu = bitterness.calc_ibu
  end

  def calc_color
    color = CalculateColor.new(malts_to_array)
    @srm = color.calc_srm
  end

  def display_hops
    show_hops = DisplayHops.new(hops_to_array)
    show_hops.display
  end

  def display_malts
    show_malts = DisplayMalts.new(malts_to_array)
    show_malts.display
  end

  def select_by_yeast
    by_yeast = SelectByYeast.new(@yeast)
    by_yeast.select
  end

  def select_by_malt(style_list)
    by_malts = SelectByMalts.new(malt_names_to_array)
    by_malts.select(style_list)
  end

  def select_by_aroma(style_list)
    by_aroma = SelectByAroma.new(@hops)
    by_aroma.select(style_list)
  end

  def select_by_abv(style_list)
    by_abv = SelectByAbv.new(@abv)
    by_abv.select(style_list)
  end

  def select_by_ibu(style_list)
    by_ibu = SelectByIbu.new(@ibu)
    by_ibu.select(style_list)
  end

  def select_by_srm(style_list)
    by_srm = SelectBySrm.new(@srm)
    by_srm.select(style_list)
  end

  def filter_possible_styles
    style_list = select_by_aroma(select_by_malt(select_by_yeast))
    select_by_abv(style_list) & select_by_ibu(style_list) & select_by_srm(style_list)
  end

  def assign_style
    style_list = filter_possible_styles
    if style_list.length == 1
      @style = style_list[0]
    elsif style_list.length > 1
      @style = filter_style_by_ingredients(style_list)
    end
    # needs better case handling for no style match - approximate styles
  end

  def filter_style_by_ingredients(style_list)
    tally_table = tally_common_ingredients(style_list)
    malt_tally = tally_table[0]
    hop_tally = tally_table[1]
    tally = malt_tally.merge(hop_tally) { |style, m_count, h_count| m_count + h_count }
    tally = (tally.sort_by { |style, count| -count })
    tally = tally.first
    return tally[0]
  end

  def tally_common_ingredients(style_list)
    ingredients = TallyIngredients.new(malt_names_to_array, hop_names_to_array)
    ingredients.tally_common(style_list)
  end

end

app/models/style.rb
class Style < ActiveRecord::Base
  validates( :name, { :uniqueness => { :case_sensitive => false } } )
end

app/models/yeast.rb
class Yeast < ActiveRecord::Base
  validates( :name, :uniqueness => { :case_sensitive => false } )
  validates( :attenuation, :numericality => { :greater_than => 50, :less_than => 100 } )
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipe_controller.rb
class RecipeController < ApplicationController

  def new
    @recipe = Recipe.new
    @recipe.choose_attributes
  end

  def show
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title)
    base_title = "Wamibrew"
    if page_title.empty?
        base_title
      else
        "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/hops_helpers.rb
module HopsHelpers

  def self.pull_hop_object(hop_ary)
    hop_ary[0]
  end

  def self.pull_hop_name(hop_ary)
    hop_ary[0].name
  end

  def self.pull_hop_amt(hop_ary)
    hop_ary[1][0]
  end

  def self.pull_hop_time(hop_ary)
    hop_ary[1][1]
  end

end

app/helpers/malt_helpers.rb
module MaltHelpers

  def self.pull_malt_object(malt_ary)
    malt_ary[0]
  end

  def self.pull_malt_name(malt_ary)
    malt_ary[0].name
  end

  def self.pull_malt_amt(malt_ary)
    malt_ary[1]
  end

end

app/helpers/name_helpers.rb
module NameHelpers

  def self.capitalize_titles(title)
    (title.split(" ").collect { |word| word.capitalize }).join(" ")
  end

  def self.check_smash_name(name)
    name.include?("SMASH") ? true : false
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    wamibrew by
    <a href="http://davidroberts.xyz">David Roberts</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Help",    help_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <%= link_to "wamibrew", root_path, id: "logo" %>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>

</body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/recipe/_recipe_table.html.erb
<div id="ingredients">
  <h3>Ingredients</h3>
  <ul>
    <li>
      malt: <%= @recipe.display_malts %>
    </li>
    <li>
      hops: <%= @recipe.display_hops %>
    </li>
    <li>
      yeast: <%= @recipe.yeast.name %>
    </li>
  </ul>
</div>
<div id="specifications">
  <h3>Specifications</h3>
  <ul>
    <li>abv: <%= @recipe.abv %>%</li>
    <li>ibu: <%= @recipe.ibu %></li>
    <li>color: <%= @recipe.srm %> srm</li>
  </ul>
</div>

app/views/recipe/new.html.erb
<% provide(:title, "Try Brewing...") %>
<h1>Try Brewing...</h1>
<div class="center hero-unit">
  <p>
    <div id="recipe_name">
      <%= @recipe.name %>
    </div>
  </p>
</div>
<div id="recipe_format">
  <%= render 'recipe_table' %>
</div>

<div class="center hero-unit">
  <p><h2>Not what you had in mind?</h2>
  <%= link_to "What Else Am I Brewing?", new_recipe_path,
                                class: "btn btn-large btn-default" %>
  </p>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<div class="left hero-unit">
  <h1>About</h1>
  <p>What Am I Brewing? (Wamibrew) is a smart beer recipe generator for homebrewers.</p>
  <p>By <a href="http://davidroberts.xyz">David Roberts</a></p>
  <p>How it works...</p>
  <p>
    <ul>
      <li>
        When you ask Wamibrew what to brew, it randomly generates a brew-able recipe and then attempts to heuristically
        determine what style of beer most closely matches the generated recipe based on calculated attributes.  Every recipe is guaranteed to make beer!...
        of some kind.
      </li>
      <li>
        Wamibrew uses the spontaneity of random numbers to suggest fun and interesting takes on beer styles - it is not meant to generate the "perfect" porter,
        stout, or IPA, and your results may differ.
      </li>
   </ul>
  </p>
  <p>Calculations:
    <ul>
      <li>
        Equipment: Wamibrew generates five gallon all-grain recipes and assumes a standard mash efficiency of 70%.
        Information regarding conversions for malt extract or batch size can be found through links in the <%= link_to "help", help_path %> section.
      </li>
      <li>
        Bitterness: Wamibrew uses a modified version of Jackie Rager's method to calculate IBUs, adjusted to
        more closely match Glenn Tinseth's more recent method.  For a full discussion and source formulae see
        Norm Pyle's <a href="http://www.realbeer.com/hops/FAQ.html#units">excellent article</a> on the subject.
      </li>
      <li>
        Hops: Alpha acid data from <a href="http://hopunion.com/">Hop Union</a>
      </li>
      <li>
        Grains: Malt potential, yield, and SRM values are based manufacturer data when possible, e.g. <a href="http://www.briess.com/">Briess Malting</a>.
      </li>
      <li>
        Yeast: Wamibrew uses a standard Alcohol by Volume calculation based on an averaged yeast attenuation value by strain.
        Values from <a href="https://www.wyeastlab.com/">Wyeast</a> and <a href="http://www.whitelabs.com/">White Labs</a> respectively.
      </li>
      <li>
        Style: Styles are based on<a href="http://www.bjcp.org/">BJCP</a> guidelines with additions made for newer/hybrid styles (Session IPA, Wheat Wine, etc.)
      </li>
    </ul>
  </p>
  <p>Planned Features:
    <ul>
      <li>
        Generate recipes by style, season, and other attributes
      </li>
      <li>
        Approximate recipe assignments (e.g. White IPA-ish)
      </li>
      <li>
        Fun names
      </li>
      <li>
        Ability to retain or 'freeze' ingredients from one recipe to the next
      </li>
    </ul>
  </p>
<div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<div class="left hero-unit">
  <h1>Contact</h1>
  <p>
    <a href="http://github.com/smoip/wamibrew">github project page</a>
  </p>
  <p>
    <a href="mailto:drsmoip@gmail.com?Subject=wamibrew" target="_top">
    email</a>
    <!-- Refactor with form -->
  </p>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<div class="left hero-unit">
  <h1>Help</h1>
  <p>Wamibrew is a work in progress.  For general brewing help or
    for more information please consult one of these external resources.</p>
  <h2>Other Resources</h2>
  <p>General information:
    <ul>
      <li>
        Charlie Papazian's Classic
        <a href="http://en.wikipedia.org/wiki/Charlie_Papazian#Complete_Joy_of_Home_Brewing">Joy of Homebrewing</a>
      </li>
      <li>
        John Palmer's excellent <a href="http://www.howtobrew.com">How to Brew</a>
      </li>
      <li>
        <a href="http://www.homebrewtalk.com">Homebrew Talk</a> Forums
      </li>
    </ul>
  </p>
  <p>Recipe design software:
    <ul>
      <li>
        <a href="http://beersmith.com">BeerSmith</a> (paid download)
      </li>
      <li>
        Mark Riley's <a href="http://hbd.org/recipator/">Beer Recipator</a> (free web app)
      </li>
    </ul>
  </p>
</div>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Wamibrew</h1>
  <p>the smart homebrew recipe generator</p>
  <div id="initial-button-box">
    <%= link_to "What Am I Brewing?", new_recipe_path,
                                class: "btn btn-large btn-default" %>
  </div>
</div>